---
title: "2020-03-30_Training.Rmd"
author: "Zach"
date: "2020-03-30"
output: html_document
---

Hello, and welcome to a summary the first training session for bio-group technical
development!  This is an Rmarkdown document that will walk you through what we 
did in the first session on March 30, 2020.

With the myriad statistics of the novel coronavirus pervading most media outlets, 
we opted to examine the data ourselves to obtain a clearer understanding of the 
spread of the disease.  We opted to use the dataset maintained bythe Johns Hopkins 
University Center for Systems Science and Engineering (JHU CSSE), for two main
reasons:

    1) They maintain a most excellent data dashboard located here: 
    (https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6) 
    Of particular interest to us is the spatial location data, meaning that we too
    can generate our own maps from these data.  Thanks to Kelsey for the original 
    share!
    
    2) The entire dataset is conveniently located on github 
    (https://github.com/CSSEGISandData/COVID-19), updated daily, and is entirely 
    contained within comma-separated-values files (.csv files).  Many modern 
    programming languages,including R and Python, have libraries or packages that 
    interface well with .csv files, making it a breeze to ingest, manipulate, and 
    analyze the data within!
    
In the code below, we will walk through the initial setup of this project, which
includes dowloading, cleaning, and organizing the data, and we will finish by
generating a plot of the daily mortality rate in the U.S. as well as the total 
to-date U.S. mortality count.  The code is organized so that we may easily adapt
and expand upon it to answer other questions of interest, which so far have
includued adding country population counts to the dataset and generating animated
heatmaps of infections/deaths/recoveries over time.  Together, hopefully we will
create some meaning from this unique situation and grow our knowledge and skillsets
to better ourselves and our communities!  


    

